# Generated by Django 4.0.4 on 2022-06-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=50)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('numer_domu', models.CharField(max_length=5)),
                ('numer_lokalu', models.CharField(blank=True, max_length=5, null=True)),
                ('imie', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.kategoria')),
            ],
            options={
                'verbose_name': 'Podkategoria',
                'verbose_name_plural': 'Podkategorie',
            },
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('czy_zamowiony', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now=True)),
                ('data_zamowienia', models.DateTimeField(null=True)),
                ('rozmiar', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Pozycja zamówienia',
                'verbose_name_plural': 'Pozycje zamówień',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('opis', models.CharField(blank=True, max_length=500)),
                ('zdjecie_glowne', models.ImageField(null=True, upload_to='images')),
                ('podkategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.podkategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='RodzajePlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rodzaje Platnosci',
                'verbose_name_plural': 'Rodzaje Platnosci',
            },
        ),
        migrations.CreateModel(
            name='RodzajWysylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Rodzaj Wysyłki',
                'verbose_name_plural': 'Rodzaje Wysyłki',
            },
        ),
        migrations.CreateModel(
            name='Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozmiar', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Rozmiar',
                'verbose_name_plural': 'Rozmiary',
            },
        ),
        migrations.CreateModel(
            name='Zdjecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(null=True, upload_to='images')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
            ],
            options={
                'verbose_name': 'Zdjecie',
                'verbose_name_plural': 'Zdjecia',
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateField()),
                ('data_wyslania', models.DateField(null=True)),
                ('data_dostarczenia', models.DateField(null=True)),
                ('czy_zamowione', models.BooleanField(default=False)),
                ('czy_oplacono', models.BooleanField(default=False)),
                ('adres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.adres')),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
                ('pozycje_zamowienia', models.ManyToManyField(to='sklep.pozycjazamowienia')),
                ('rodzaj_wysylki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rodzajwysylki')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
        migrations.CreateModel(
            name='Produkt_Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_dostepnego', models.PositiveIntegerField()),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
                ('rozmiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rozmiar')),
            ],
            options={
                'verbose_name': 'Produkt_Rozmiar',
                'verbose_name_plural': 'Produkty i rozmiary',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='produkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt'),
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_zaksiegowania', models.DateTimeField(null=True)),
                ('rodzaj_platnosci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rodzajeplatnosci')),
                ('zamowienie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.zamowienie')),
            ],
            options={
                'verbose_name': 'Płatności',
                'verbose_name_plural': 'Płatności',
            },
        ),
        migrations.CreateModel(
            name='Opinie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.CharField(max_length=400)),
                ('ocena', models.IntegerField()),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
            },
        ),
        migrations.CreateModel(
            name='KartyPlatnicze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=16)),
                ('cvc', models.CharField(max_length=3)),
                ('miesiac', models.CharField(max_length=2)),
                ('rok', models.CharField(max_length=2)),
                ('klient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
            ],
            options={
                'verbose_name': 'Karta Płatnicza',
                'verbose_name_plural': 'Karty Płatnicze',
            },
        ),
        migrations.AddField(
            model_name='adres',
            name='klient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient'),
        ),
    ]
