# Generated by Django 4.0.4 on 2022-11-12 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kartyplatnicze',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='Zły numer', regex='^.{3}$')]),
        ),
        migrations.AlterField(
            model_name='kartyplatnicze',
            name='numer',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='nomatch', message='Zły numer', regex='^.{16}$')]),
        ),
    ]
