# Generated by Django 3.1.14 on 2022-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_auto_20221026_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='ulub_produkty',
            field=models.ManyToManyField(to='sklep.Produkt'),
        ),
    ]
