# Generated by Django 3.1.14 on 2022-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_klient_ulub_produkty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='ulub_produkty',
            field=models.ManyToManyField(related_name='client_set', to='sklep.Produkt'),
        ),
    ]
