# Generated by Django 3.1.14 on 2022-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_auto_20221026_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pytania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.CharField(max_length=1000)),
                ('odpowiedz', models.CharField(max_length=1000)),
            ],
        ),
    ]
