# Generated by Django 3.1.14 on 2022-10-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_pytania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pytania',
            old_name='odpowiedz',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='pytania',
            old_name='tresc',
            new_name='question',
        ),
    ]
