# Generated by Django 3.1.14 on 2022-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_auto_20221027_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='ulub_produkty',
            field=models.ManyToManyField(related_name='clients', to='sklep.Produkt'),
        ),
    ]
